#!/usr/bin/env python3
"""Registration experiment harness.

Runs one (source, target) pair through several CloudCropper registration
backends, appends the results to experiments/registration-results.csv, and
regenerates the LaTeX results table included by the algorithm-notes PDF
(docs/organize/tables/registration-results.tex).

Usage:
    scripts/reg-bench.py <source> <target> [--label case01]
        [--algos gicp,kiss-gicp,gsdf] [--gpu] [--save-aligned DIR]
        [--binary PATH] [--extra "--reg-kiss-res 0.1"]

stdlib only; the parsing matches `cloudcropper register` stdout.
"""
import argparse
import csv
import datetime
import re
import shlex
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_PATH = REPO / "experiments" / "registration-results.csv"
TEX_PATH = REPO / "docs" / "organize" / "tables" / "registration-results.tex"
CSV_FIELDS = ["date", "label", "source", "target", "algo", "converged",
              "rmse", "inliers", "time_s", "confidence", "detail", "transform"]
# gsdf(-gpu) needs the python torch env, so it is opt-in via --gpu.
DEFAULT_ALGOS = "gicp,kiss-gicp"


def find_binary(explicit: str | None) -> Path:
    if explicit:
        p = Path(explicit)
        if p.is_file():
            return p
        sys.exit(f"error: binary not found: {explicit}")
    for preset in ("vcpkg", "gui"):
        p = REPO / "build" / preset / "src" / "app" / "cloudcropper"
        if p.is_file():
            return p
    sys.exit("error: cloudcropper binary not found (build the vcpkg/gui preset"
             " or pass --binary)")


def run_one(binary: Path, source: str, target: str, algo: str,
            extra: list[str], aligned: Path | None) -> dict:
    cmd = [str(binary), "register", source, target, "--reg-algo", algo, *extra]
    if aligned:
        cmd += ["-o", str(aligned)]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)
    out, err = proc.stdout, proc.stderr

    row = {"algo": algo, "converged": "", "rmse": "", "inliers": "",
           "time_s": "", "confidence": "", "detail": "", "transform": ""}
    m = re.search(r"converged:\s*(\S+)\s+rmse:\s*(\S+)\s+inliers:\s*(\S+)"
                  r"\s+time:\s*([\d.]+)s", out)
    if m:
        row.update(converged=m.group(1), rmse=m.group(2),
                   inliers=m.group(3), time_s=m.group(4))
        cm = re.search(r"confidence:\s*([\d.]+)", out)
        if cm:
            row["confidence"] = cm.group(1)
        tail = [l.strip() for l in out[m.end():].strip().splitlines()
                if l.strip() and not l.startswith("confidence:")]
        if tail:
            row["detail"] = tail[0]
        nums = re.findall(r"\[\s*([-\d.eE+\s]+)\]", out)
        vals = " ".join(" ".join(n.split()) for n in nums[:4])
        if len(vals.split()) == 16:
            row["transform"] = vals
    else:
        last = (err.strip() or out.strip()).splitlines()
        row["converged"] = "error"
        row["detail"] = last[-1][:200] if last else f"exit {proc.returncode}"
    return row


def tex_escape(s: str) -> str:
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


def regenerate_tex(rows: list[dict]) -> None:
    TEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% AUTO-GENERATED by scripts/reg-bench.py - do not edit by hand.",
        "% Source of truth: experiments/registration-results.csv",
        r"\begin{longtable}{p{0.24\linewidth}p{0.13\linewidth}llrrrr}",
        r"\toprule",
        r"\textbf{case (source $\to$ target)} & \textbf{algo} & \textbf{conv.} & "
        r"\textbf{rmse} & \textbf{inliers} & \textbf{conf.} & "
        r"\textbf{time(s)} & \textbf{date} \\",
        r"\midrule",
    ]
    if not rows:
        lines.append(r"\multicolumn{8}{c}{(no experiments recorded yet)} \\")
    for r in rows:
        conv = {"yes": r"$\circ$", "no": r"$\times$"}.get(
            r["converged"], r"\textbf{err}")
        date = r["date"][:16].replace("T", " ")
        label = tex_escape(r["label"]).replace("->", r"$\to$")
        lines.append(
            f"{label} & {tex_escape(r['algo'])} & {conv} & "
            f"{tex_escape(r['rmse'] or '-')} & {tex_escape(r['inliers'] or '-')} & "
            f"{tex_escape(r.get('confidence') or '-')} & "
            f"{tex_escape(r['time_s'] or '-')} & {date} \\\\")
    lines += [r"\bottomrule", r"\end{longtable}", ""]
    TEX_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("target")
    ap.add_argument("--algos", default=DEFAULT_ALGOS)
    ap.add_argument("--gpu", action="store_true",
                    help="also run gsdf-gpu (needs python torch env)")
    ap.add_argument("--label", default="")
    ap.add_argument("--save-aligned", default="",
                    help="write aligned source per algo into this dir")
    ap.add_argument("--binary", default="")
    ap.add_argument("--extra", default="",
                    help="passthrough flags for `register` (quoted)")
    args = ap.parse_args()

    for f in (args.source, args.target):
        if not Path(f).exists():
            sys.exit(f"error: no such file: {f}")
    binary = find_binary(args.binary or None)
    label = args.label or (Path(args.source).stem + " -> " + Path(args.target).stem)
    algos = [a.strip() for a in args.algos.split(",") if a.strip()]
    if args.gpu and "gsdf-gpu" not in algos:
        algos.append("gsdf-gpu")
    extra = shlex.split(args.extra)
    aligned_dir = Path(args.save_aligned) if args.save_aligned else None
    if aligned_dir:
        aligned_dir.mkdir(parents=True, exist_ok=True)

    stamp = datetime.datetime.now().isoformat(timespec="seconds")
    new_rows, failures = [], 0
    for algo in algos:
        aligned = (aligned_dir / f"{label}_{algo}.ply") if aligned_dir else None
        print(f"== {algo} ==", flush=True)
        row = run_one(binary, args.source, args.target, algo, extra, aligned)
        row.update(date=stamp, label=label, source=args.source,
                   target=args.target)
        new_rows.append(row)
        if row["converged"] == "error":
            failures += 1

    # append to the CSV (source of truth); migrate old headers in place
    CSV_PATH.parent.mkdir(parents=True, exist_ok=True)
    exists = CSV_PATH.exists()
    if exists:
        with CSV_PATH.open(newline="", encoding="utf-8") as f:
            rd = csv.DictReader(f)
            if rd.fieldnames != CSV_FIELDS:
                old_rows = [{k: (r.get(k) or "") for k in CSV_FIELDS} for r in rd]
                with CSV_PATH.open("w", newline="", encoding="utf-8") as g:
                    w = csv.DictWriter(g, fieldnames=CSV_FIELDS)
                    w.writeheader()
                    w.writerows(old_rows)
    with CSV_PATH.open("a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        if not exists:
            w.writeheader()
        w.writerows(new_rows)

    # regenerate the LaTeX table from the FULL history
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        all_rows = sorted(csv.DictReader(f),
                          key=lambda r: (r["date"], r["label"], r["algo"]))
    regenerate_tex(all_rows)

    # console summary of this run
    print(f"\n{'algo':<12} {'conv':<6} {'rmse':<12} {'inliers':<9} "
          f"{'conf':<6} {'time(s)':<8} detail")
    for r in new_rows:
        print(f"{r['algo']:<12} {r['converged']:<6} {r['rmse'] or '-':<12} "
              f"{r['inliers'] or '-':<9} {r['confidence'] or '-':<6} "
              f"{r['time_s'] or '-':<8} {r['detail'][:56]}")
    print(f"\nappended {len(new_rows)} rows -> {CSV_PATH.relative_to(REPO)}"
          f"   (total {len(all_rows)})")
    print(f"regenerated            -> {TEX_PATH.relative_to(REPO)}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
